<a href="https://colab.research.google.com/github/MiltonGallardo/MiltonGallardo/blob/main/Tarea%20semana%204/matriz_confusion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio de trazado de matriz de confusión
# Milton Gallardo

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from sklearn.metrics import confusion_matrix
from string import ascii_uppercase




In [ ]:
y_verd=np.array([87,17])
y_pred=np.array([16,59])

In [ ]:
cnfm=confusion_matrix(y_verd,y_pred)

In [ ]:
print(cnfm)


[[0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [1 0 0 0]]
